server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring_security?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: Abc@1234.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: "YourSuperSecretKeyForJwtSigningWhichShouldBeAtLeast32Characters"
    expiration: 900000       # 15 minutes in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    org:
      springframework: DEBUG
